services:
  api1: &api
    build: .
    hostname: api1
    depends_on:
      - db
    environment:
      PORT: 8080
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 0.4GB

  api2:
    <<: *api
    hostname: api2

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9999:9999
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: 0.3GB

  db:
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    deploy:
      resources:
        limits:
          cpus: 0.8
          memory: 1.9GB
