services:
  api1: &api
    build: .
    network_mode: host
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 0.5GB

  api2:
    <<: *api
    environment:
      PORT: 3001

  nginx:
    image: nginx
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 0.5GB

  db:
    image: postgres
    network_mode: host
    command: postgres -c config_file=/etc/postgres/postgresql.conf
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/etc/postgres/postgresql.conf
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    deploy:
      resources:
        limits:
          cpus: 0.75
          memory: 1.5GB
